### PR TITLE
Upgrade to Twirl 1.3.2

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
@JakeWharton I've updated this PR, so you should be able to take a look now

**Comment by benmccann** [comment]
@JakeWharton would you be able to merge this one?

**Comment by benmccann** [comment]
@JakeWharton Play 2.6 is officially out now, so it would be nice to get this change in

**Comment by JakeWharton** [comment]
Yep. Will do this weekend or next week. Thanks!

**Comment by mkurz** [comment]
@benmccann Twirl 1.3.3 is out

**Comment by JakeWharton** [comment]
Merged manually with 1.3.3. Thanks!

**Comment by benmccann** [comment]
Thanks!

**Pull request closed without merging**
